# Generated by Django 5.2.3 on 2025-06-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_blog_delete_recepie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='description',
        ),
    ]
