# Generated by Django 5.2.3 on 2025-06-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_rename_description_blog_content_blog_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='related_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
